const translation = {
  jobs: 'Работа',
  talants: 'Таланты',
  contact: 'Kонтакт',
  about: 'О нас',

  profile: 'Профиль',
  notification: 'Уведомление',
  contracts: 'Контракты',
  chats: 'Чаты',
  resume: 'Резюме',
  log_out: 'Выйти',
  my_jobs: 'Мои работы',

  filter: 'Фильтр',
  payment: 'К оплате',
  from: 'От',
  to: 'К',
  duration: 'Продолжительность',
  more_than_1: 'Больше, чем 80%',
  required_level: 'Требуемый уровень',
  verified: 'Проверено',
  region: 'Область',
  complated_jobs_minimum: 'Выполненные работы (минимум)',
  required_skills: 'Требуемые навыки',
  apply_filters: 'Применить фильтр',
  select_region: 'Выберите регион',
  select_items: 'Выберите элементы',

  job_success: 'Успех в работе',
  hourly: 'Ежечасно',
  portfolio: 'Портфолио',
  work_history: 'История работы',
  completed: 'Завершенный',
  in_progress: 'В ходе выполнения',
  total_earnings: 'Общий доход',
  total_jobs: 'Всего работы',
  available: 'Доступный',
  more_than: 'Более',
  'hrs/week': ' часов в неделю',
  verifications: 'Проверки',
  language: 'Языки',
  educations: 'Образование',
  location: 'Местоположение',
  experience: 'Опыт',
  skills: 'Навыки',
  contacts: 'Контакты',
  living_address: 'Живой адрес',
  member_since: 'Участник с',

  no_internet: 'нет соединения с интернетом',
};

export default translation;
