const translation = {
  jobs: 'Ish',
  talants: "Iste'dodlar",
  contact: "Bog'lanish",
  about: 'Biz haqimizda',

  profile: 'Profil',
  notification: 'Bildirishnoma',
  contracts: 'Shartnomalar',
  chats: 'Suhbatlar',
  resume: 'Rezyume',
  log_out: 'Chiqish',
  my_jobs: 'Mening ishlarim',

  filter: 'Filtr',
  payment: "To'lov miqdori",
  from: 'Dan',
  to: 'Gacha',
  duration: 'Davomiyligi',
  more_than_1: "80% dan ko'proq",
  required_level: 'Majburiy daraja',
  verified: 'Tasdiqlangan',
  region: 'Mintaqa',
  complated_jobs_minimum: 'Tugallangan ishlar (minimal)',
  required_skills: "Kerakli ko'nikmalar",
  apply_filters: "Filterni qo'llash",
  select_region: 'Mintaqani tanlang',
  select_items: 'Elementlarni tanlang',

  job_success: 'Ishda muvaffaqiyat',
  hourly: 'Soatlik',
  portfolio: 'Portfolio',
  work_history: 'Ish tarixi',
  completed: 'Bajarildi',
  in_progress: 'Jarayonda',
  total_earnings: 'Umumiy daromad',
  total_jobs: 'Hamma ishlar',
  available: 'Mavjud',
  more_than: 'Haftada',
  'hrs/week': 'soatdan ortiq',
  verifications: 'Tekshiruvlar',
  language: 'Tillar',
  educations: "Ta'lim",
  location: 'Manzil',
  experience: 'Tajriba',
  skills: "Ko'nikmalar",
  contacts: 'Kontaktlar',
  living_address: 'Yashash manzili',
  member_since: "A'zo bo'lgan vaqti",

  no_internet: "internet aloqasi yo'q",
};

export default translation;
