const translation = {
  jobs: 'Jobs',
  talants: 'Talants',
  contact: 'Contact us',
  about: 'About us',

  profile: 'Profile',
  notification: 'Notification',
  contracts: 'Contracts',
  chats: 'Chats',
  resume: 'Resume',
  log_out: 'Log out',
  my_jobs: 'My Jobs',

  filter: 'Filter',
  payment: 'Payment amount',
  from: 'From',
  to: 'To',
  duration: 'Duration',
  more_than_1: 'More than 80%',
  required_level: 'Required level',
  verified: 'Verified',
  region: 'Region',
  complated_jobs_minimum: 'Completed jobs (minimum)',
  required_skills: 'Required skills',
  apply_filters: 'Apply filter',
  select_region: 'Select region',
  select_items: 'Select items',

  job_success: 'Job success',
  hourly: 'Hourly',
  portfolio: 'Portfolio',
  work_history: 'Work history',
  completed: 'Completed',
  in_progress: 'In progress',
  total_earnings: 'Total earnings',
  total_jobs: 'Total Jobs',
  available: 'Available',
  more_than: 'More than',
  'hrs/week': 'hrs/week',
  verifications: 'Verifications',
  language: 'Languages',
  educations: 'Educations',
  location: 'Location',
  experience: 'Experience',
  skills: 'Skills',
  contacts: 'Contacts',
  living_address: 'Living address',
  member_since: 'Member since',

  no_internet: 'no internet connection',
};

export default translation;
